config/routes.rb
Rails.application.routes.draw do

  get 'third_registers/create'
  get 'third_registers/destroy'
  get 'second_registers/create'
  get 'second_registers/destroy'
  get 'registers/create'
  get 'registers/destroy'
  get 'sessions/new'
  root 'home_pages#home'
  get '/about',   to: 'home_pages#about'
  get '/terms',     to: 'home_pages#terms'
  get '/privacy',  to: 'home_pages#privacy'
  get '/started_page',  to: 'home_pages#started_page'
  get '/signup',     to: 'users#new'
  post  '/signup',     to: 'users#create'
  get '/impressions_page',   to: 'users#impressions_page'
  get '/all_impressions_page',   to: 'users#all_impressions_page'
  get '/readed_books_table',   to: 'users#readed_books_table'
  get  '/login',     to: 'sessions#new'
  post  '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get  '/reading_books',  to:  'books#reading_books'
  get  '/readed_books',  to:  'books#readed_books'
  post  '/readed_books',  to:  'books#readed_books'
  get  '/want_books',  to:  'books#want_books'
  get  '/impressions_title',  to:  'impressions#impressions_title'
  post  '/impressions_title',  to:  'impressions#impressions_title'

  resources :users
  resources :impressions, only: %i[create destroy edit update]
  resources :registers, only: %i[create destroy]
  resources :second_registers, only: %i[create destroy]
  resources :third_registers, only: %i[create destroy]
  resources :books, only: %i[index create show] do
  	collection do
     get :search
    end		
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
 	before_save :downcase_email
    
    # アバター用アップローダー
    mount_uploader :avatar, AvatarUploader
	# nameのヴァリデーション
	validates :name, presence: true, length: { maximum: 39 }
	# emailのヴァリデーション
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
			  format: { with: VALID_EMAIL_REGEX },
	          uniqueness: { case_sensitive: false }
	# passwordのヴァリデーション
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	has_secure_password

## アソシエーション
     has_many :registers, dependent: :destroy
     has_many :second_registers, dependent: :destroy
     has_many :third_registers, dependent: :destroy
     has_many :impressions, dependent: :destroy
     
     has_many :reading_books, through: :registers, source: :book
     has_many :readed_books, through: :second_registers, source: :book
     has_many :want_books, through: :third_registers, source: :book

     has_many :authorizations, dependent: :destroy
## ログイン機能関連メソッド
    # 渡された文字列のハッシュ値を返す
    def self.digest(string)
     cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
     BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def self.new_token
     SecureRandom.urlsafe_base64
    end

    # ダミーメール生成
    def self.dammy_email
     p [*"a".."z", *"A".."Z", *"0..9"].sample(18)*"" + "@" + "rerec.com"
    end
    
    # 永続セッションのためにユーザーをデータベースに記憶する
    def remember
     self.remember_token = User.new_token
     update_attribute(:remember_digest, User.digest(remember_token))
    end

    # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(attribute, token)
     digest = send("#{attribute}_digest")
     return false if digest.nil?
     BCrypt::Password.new(digest).is_password?(token)
    end
    
    # ユーザーのログイン情報を破棄する
    def forget
     update_attribute(:remember_digest, nil)
    end

    # 読んでいる本に登録
    def reading_book_register(book)
     reading_books << book
    end

    # 読んでいる本から削除
    def reading_book_un_register(book)
     reading_books.destroy(book)
    end
    
    # 渡された本の情報が登録済みであればtrueを返す
    def reading_book_register?(book)
     reading_books.include?(book)
    end
    
    ## 読んだ本に登録
    def readed_book_register(book)
     readed_books << book
    end
    
    ## 読んだ本から削除
    def readed_book_un_register(book)
     readed_books.destroy(book)
    end

    ## 渡された本の情報が登録済みであればtrueを返す
    def readed_book_register?(book)
     readed_books.include?(book)
    end
    
    ### 読みたい本に登録
    def want_book_register(book)
     want_books << book
    end
    
    ### 読みたい本から削除
    def want_book_un_register(book)
     want_books.destroy(book)
    end
    
    ### 渡された本の情報が登録済みであればtrueを返す
    def want_book_register?(book)
     want_books.include?(book)
    end

    # OAuth関連メソッド authからユーザーをcreate
    def User.create_from_auth!(auth)
      token = User.new_token
      digest = User.digest(token)
      email = User.dammy_email
     if auth['info']['email'].nil?# twitterはemailがnilなので、上段でtwitter取得。下段でfacebookのauth取得
      User.create!(:name => auth['info']['name'], :email => email, :uid => auth['uid'], :provider => auth['provider'], :oauth_token => auth["credentials"], :password_digest => digest)
     else
      User.create!(:name => auth['info']['name'], :email => auth['info']['email'], :uid => auth['uid'], :provider => auth['provider'], :oauth_token => auth["credentials"], :password_digest => digest)
     end
    end
private
	  # メールアドレスを全て小文字に変換する
	  def downcase_email
	  	email.downcase!
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :destroy, :impressions_page, :all_impressions_page, :readed_books_table]
  before_action :only_user, only: [:show]
  before_action :admin_user, only: [:index, :destroy]

  def index
   @user = User.all
   @users = Kaminari.paginate_array(@user).page(params[:page])
  end

  def new
   @user = User.new
  end

  def show
   date = Date.today
   now = Time.current
   @user = User.find(params[:id])
   @books = @user.reading_books.order(updated_at: :desc)
   @book_paginate = Kaminari.paginate_array(@books).page(params[:page]).per(1)
   @page_count = @user.readed_books.pluck(:page_count).sum
   @book_count = @user.readed_books.count
   @now_month_count = @user.readed_books.where(created_at: date.beginning_of_month..date.end_of_month).count
   @month_page_count = @user.readed_books.where(created_at: date.beginning_of_month..date.end_of_month).pluck(:page_count).sum
   @month_book_count = SecondRegister.where(user_id: current_user.id).group("MONTH(created_at)").count
   @year_book_count = SecondRegister.where(user_id: current_user.id).group("YEAR(created_at)").count
   @users = @user.impressions
   @impressions = Kaminari.paginate_array(@users).page(params[:page]).per(3)
   @impression = current_user.impressions.build if logged_in?
   # 読んだ本の表
   @books_table = @user.readed_books.order(created_at: :desc).pluck(:title, :author, :created_at)
   @books_table_data = Kaminari.paginate_array(@books_table).page(params[:page]).per(10)
   @table_num = Kaminari.paginate_array(@books_table).page(params[:page]).current_page
   @base_level = (@table_num - 1)*10
   # 読みたい本の表
   @want_books_table = @user.want_books.order(updated_at: :desc).pluck(:title, :author, :updated_at)
   @want_books_table_data = Kaminari.paginate_array(@want_books_table).page(params[:page]).per(10)
   @want_table_num = Kaminari.paginate_array(@want_books_table).page(params[:page]).current_page
   @want_base_level = (@want_table_num - 1)*10
   # サイト内検索機能
   unless params[:i] == "" || params[:p] == "" # 空文字対策
    if params[:i] #all_impressions_pageの検索バー
     @feed_item = Impression.where(published: true).search_by_keyword(params[:i])
      if @feed_item.any?
       @feed_items = Kaminari.paginate_array(@feed_item).page(params[:page]).per(5)
       flash.now[:success]= "#{@feed_item.count}件の投稿がヒットしました"
      else
       flash[:danger] = "“#{params[:i]}” に一致する項目が見当たりませんでした"
       redirect_to all_impressions_page_path
      end
    end
     if params[:p] #impressions_pageの検索バー
      @p_feed_item = @users.search_by_keyword(params[:p])
       if @p_feed_item.any?
        @p_feed_items = Kaminari.paginate_array(@p_feed_item).page(params[:page]).per(5)
        flash.now[:success]= "#{@p_feed_item.count}件の投稿がヒットしました"
       else
        flash[:danger] = "“#{params[:p]}” に一致する項目が見当たりませんでした"
        redirect_to impressions_page_path
       end
     end
   end
  end
  
  def create
   @user = User.new(user_params)
    if @user.save
   	 flash[:success] = "登録が完了しました"
   	 redirect_to @user
     log_in @user
    else
     flash.now[:danger] = '名前、メールアドレスが無効か、パスワードが不一致のようです'
   	 render 'new'
    end
  end
  
  def destroy
   User.find(params[:id]).destroy
   flash[:success] = "削除しました"
   redirect_to users_url
  end
  
  def impressions_page
   @user = User.find_by(id: current_user.id)
   @users = @user.impressions.order(updated_at: :desc)
   @impressions = Kaminari.paginate_array(@users).page(params[:page]).per(5)
   @impression = current_user.impressions.build if logged_in?
  end

  def all_impressions_page
   @all_impression = Impression.where(published: true).order(updated_at: :desc)
   @all_impressions = Kaminari.paginate_array(@all_impression).page(params[:page]).per(5)
   flash.now[:info] = "投稿内容にはネタバレが含まれる場合があります"
  end

  def readed_books_table
    @user = User.find(current_user.id) 
    @books_table = @user.readed_books.order(created_at: :desc).pluck(:title, :author, :created_at)
    @books_table_data = Kaminari.paginate_array(@books_table).page(params[:page]).per(10)
    @table_num = Kaminari.paginate_array(@books_table).page(params[:page]).current_page
    @base_level = (@table_num - 1)*10
  end
   
private

	  def user_params
	   params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

    # アクセスしてきたユーザーとログイン中のユーザー（current_user）が同一でなければroot_urlに転送させ論理値を返す
    def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user?(@user)
    end
    
    # adminを除く通常のユーザーがログインしていない他のユーザーのshowにアクセスすると自分のshowにリダイレクト
    def only_user
     unless current_user.admin?
      @user = User.find(params[:id])
      redirect_to current_user unless current_user?(@user)
     end
    end

    # adminユーザーでないユーザーがアクセスしたらrootにリダイレクト
    def admin_user
     redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
 # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 90})
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   size = options[:size]
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
   image_tag(gravatar_url, alt: user.name, class: "img-circle gravatar")
  end
end

app/views/users/_signup_form.html.erb
<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user, url: yield(:url)) do |f| %>
   <%#= render 'shared/error_messages', object: f.object %>

   <%= f.label :お名前 %>
   <%= f.text_field :name, :placeholder =>  '例）Yōsuke', class: 'form-control' %>

   <%= f.label :メールアドレス %> 
   <%= f.email_field :email, :placeholder => '例）Yōsuke@rerec.com', class: 'form-control' %>

   <%= f.label :パスワード %>
   <%= f.password_field :password, :placeholder => "8文字以上", class: 'form-control' %>
   <%= f.label :password_confirmation, 'パスワード（確認入力）' %>
   <%= f.password_field :password_confirmation, :placeholder => "8文字以上", class: 'form-control' %>
   <%= f.submit yield(:button), class: "btn btn-primary" %>
  <% end %>
 </div>
</div>

app/views/users/_user.html.erb
<li>
 <%= gravatar_for user, size: 60 %>
 <%= link_to user.name, user_path(user) %>
  | <%= link_to "削除", user, method: :delete, data: { confirm: '本当に削除しますか?' } %>
</li>

app/views/users/all_impressions_page.html.erb
<% provide :title, "みんなの読書メモ" %>
  <div style="margin-top: -30px; text-align: center;">
   <%= link_to "本をさがす", search_books_path, class: "btn-border" %>
   <%= link_to "読んでいる本", reading_books_path, class: "btn-border-2" %>
   <%= link_to "読んだ本", readed_books_path, class: "btn-border-2" %>
   <%= link_to "読みたい本", want_books_path, class: "btn-border-2" %>
   <%= link_to "読書メモ確認", impressions_page_path, class: "btn-border" %>
   <%= link_to "読んだ本一覧", readed_books_table_path, class: "btn-border" %>
  </div>
<% if @all_impressions.any? %> 
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読書メモ一覧 （投稿数：<%= @all_impressions.count %>） -</h3>
  <%= render @all_impressions %>
  <%= paginate @all_impressions %>
 <% else %> 
 <hr style="border-top">
  <p style="text-align: center;">読書メモの記録はありません</p>
 <hr style="border-bottom">
 <% end %>

app/views/users/impressions_page.html.erb
<% provide :title, "読書メモ" %>
  <div style="margin-top: -30px; text-align: center;">
   <%= link_to "本をさがす", search_books_path, class: "btn-border" %>
   <%= link_to "読んでいる本", reading_books_path, class: "btn-border-2" %>
   <%= link_to "読んだ本", readed_books_path, class: "btn-border-2" %>
   <%= link_to "読みたい本", want_books_path, class: "btn-border-2" %>
   <%= link_to "読書メモ確認", impressions_page_path, class: "btn-border" %>
   <%= link_to "読んだ本一覧", readed_books_table_path, class: "btn-border" %>
  </div>
<% if @impressions.any? %>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読書メモ （投稿数：<%= @impressions.count %>） -</h3>
  <%= render @impressions %>
  <%= paginate @impressions %>
 <% else %> 
 <hr style="border-top">
  <p style="text-align: center;">読書メモの記録はありません</p>
 <hr style="border-bottom">
<% end %>

app/views/users/index.html.erb
<% provide(:title, '登録者一覧') %>
 <h1 style="font-size: 32px; font-weight: bold; margin-top: -30px; margin-bottom: 10px;">登録者一覧</h1>
　<%= paginate @users %>
　 <ul class="users"> 
   <%= render @users %>
　 </ul>
　<%= paginate @users %>

app/views/users/new.html.erb
<%= provide(:title, '新規登録') %>
<%= provide(:button, '登録') %>
<%= provide(:url, signup_path) %><!-- post先パス -->
	<div class="page-title">
	 <h1>新規登録</h1>
	</div>
   <%= render 'users/signup_form' %>

app/views/users/readed_books_table.html.erb
<%= provide(:title, '読んだ本一覧') %>
<h3 style="font-weight: bold; text-align: center; margin: -40px 0 40px ;">- 読んだ本一覧 -</h3>
<table class="table-style" style="margin: 0 auto">
 <thead>
  <tr>
   <th style="width: 15px; text-align: center;">NO</th>
   <th style="text-align: center;">本のタイトル</th>
   <th style="text-align: center;">著者名</th>
   <th style="text-align: center;">読了した日</th>
  </tr>
 </thead>
   <% @books_table_data.each_with_index do |count, i| %>
 <tbody>
  <tr>
   <td style="text-align: center; width: 15px;">
     <%= @base_level + i += 1 %><!-- 1からスタート -->
   </td>
   <td>
     <%= count[0] %>
   </td>
   <td>
    <%= count[1] %>
   </td>
   <td style="width: 10px; text-align: center;">
    <%= count[2].strftime("%Y年%-m月%-d日") %>
   </td>
  </tr>
 </tbody>
 <% end %>
</table>
<%= paginate @books_table_data %>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<!-- ヘッダーの検索バーで検索して結果がヒットした時は非表示にする -->
<% unless @feed_items.present? || @p_feed_items.present? %>
    <section style="margin-top: -50px;">
      <%= gravatar_for @user %>
      <h3 style="font-size: 20px; font-weight: bold; margin-top: 35px;"><%= @user.name %></h3><br>
     <div class="gravatar_edit">
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">アイコン画像を変更</a>
     </div>
    </section><br>  
   
  <div style="text-align: center;">
   <%= link_to "本をさがす", search_books_path, class: "btn-border" %>
   <%= link_to "読んでいる本", reading_books_path, class: "btn-border-2" %>
   <%= link_to "読んだ本", readed_books_path, class: "btn-border-2" %>
   <%= link_to "読みたい本", want_books_path, class: "btn-border-2" %>
   <%= link_to "読書メモ確認", impressions_page_path, class: "btn-border" %>
   <%= link_to "読んだ本一覧", readed_books_table_path, class: "btn-border" %>
  </div>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 今読んでいる本 -</h3>
 <% if @books.any? %> 
  <%= render @book_paginate %>
  <%= paginate @book_paginate %>
 <% else %> 
  <p style="text-align: center;">現在読んでいる本はありません</p>
 <% end %>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読んだ本の集計 -</h3>
 <%# 表 %>
<table class="table-style" style="margin: 0 auto">
 <thead>
  <tr>
   <th><% now = Time.current %><%= now.month %>月に読んだ本</th>
   <th><% now = Time.current %><%= now.month %>月に読んだページ数</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td><%= @now_month_count %>冊</td>
   <td><%= @month_page_count %>ページ</td>
  </tr>
 </tbody>
</table>
<table class="table-style" style="margin: 0 auto">
  <tr>
   <th>読んだ月(月集計)</th>
   <th>読んだ数(月集計)</th>
  </tr>
 <tr>
  <td><% @month_book_count.keys.each do |month| %>
    <%= month %>月<br>
  <% end %></td>
  <td><% @month_book_count.values.each do |count| %>
   <%= count %>冊<br>
  <% end %></td>
 </tr>
</table>

<table class="table-style" style="margin: 0 auto">
 <tr>
  <th>読んだ年(年集計)</th>
  <th>読んだ数(年集計)</th>
 </tr>
 <tr>
  <td><% @year_book_count.keys.each do |year| %>
    <%= year %>年<br>
  <% end %></td>
  <td><% @year_book_count.values.each do |book| %>
    <%= book %>冊<br>
  <% end %></td>
 </tr>
</table>

<table class="table-style" style="margin: 0 auto">
 <thead>
  <tr>
   <th>読んだ本の総計</th>
   <th>読んだページ数</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td><%= @book_count %>冊</td>
   <td><%= @page_count %>ページ</td>
  </tr>
 </tbody>
</table>

<!-- 管理者のみ -->
<% if current_user.admin? %>
<hr style="border-top: double;">
 <% if @impressions.any? %>
 <h3 style="font-weight: bold;">読書メモ （投稿数：<%= @impressions.count %>）</h3>
 <hr style="border-bottom: double;">
  <%= render @impressions %>
  <%= paginate @impressions %>
 <% end %>
 <!-- 読んだ本の表 -->
<div style="margin-top: 90px;">
 <h3 style="font-weight: bold; text-align: center; margin: -40px 0 40px ;">- 読んだ本一覧 -</h3>
  <table class="table-style" style="margin: 0 auto">
   <thead>
    <tr>
     <th style="width: 15px; text-align: center;">NO</th>
     <th style="text-align: center;">本のタイトル</th>
     <th style="text-align: center;">著者名</th>
     <th style="text-align: center;">読了した日</th>
    </tr>
   </thead>
    <% @books_table_data.each_with_index do |count, i| %>
   <tbody>
    <tr>
     <td style="text-align: center; width: 15px;">
      <%= @base_level + i += 1 %><!-- 1からスタート -->
     </td>
     <td>
      <%= count[0] %>
     </td>
     <td>
      <%= count[1] %>
     </td>
     <td style="width: 10px; text-align: center;">
      <%= count[2].strftime("%Y年%-m月%-d日") %>
     </td>
    </tr>
   </tbody>
  <% end %>
 </table>
  <%= paginate @books_table_data %>
</div>
<!-- 読みたい本の表 -->
<div style="margin-top: 90px;">
 <h3 style="font-weight: bold; text-align: center; margin: -40px 0 40px ;">- 読みたい本一覧 -</h3>
  <table class="table-style" style="margin: 0 auto">
   <thead>
    <tr>
     <th style="width: 15px; text-align: center;">NO</th>
     <th style="text-align: center;">本のタイトル</th>
     <th style="text-align: center;">著者名</th>
     <th style="text-align: center;">登録した日</th>
    </tr>
   </thead>
    <% @want_books_table_data.each_with_index do |count, i| %>
   <tbody>
    <tr>
     <td style="text-align: center; width: 15px;">
      <%= @want_base_level + i += 1 %><!-- 1からスタート -->
     </td>
     <td>
      <%= count[0] %>
     </td>
     <td>
      <%= count[1] %>
     </td>
     <td style="width: 10px; text-align: center;">
      <%= count[2].strftime("%Y年%-m月%-d日") %>
     </td>
    </tr>
   </tbody>
   <% end %>
  </table>
   <%= paginate @want_books_table_data %>
  </div>
 <% end %>
<% end %>
<!-- 管理者表示はここまで -->

<!-- 検索結果ありの場合のみ表示 -->
<!-- all_impression_page.html.erbの検索バーからのパラメータ -->
<% unless @feed_items.nil? %>
<% if logged_in? %>
 <header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
   <div class="navbar-header">
    <%= link_to "REREC", root_path, id: "logo" %>
   </div>
  <ul class="nav navbar-nav navbar-right" style="margin-right:-50px;">
    <li class="search-nav">
     <%= form_with url: user_path(current_user), method: :get, local: true do %>
    <div class="input-group">
     <%= search_field_tag "i", params[:i], class: "form-control", placeholder: "読書メモ検索" %>
    <span class="input-group-btn">
     <%= submit_tag "検索", class: "btn btn-default" %>
    </span>
    </div>
    <% end %>
    </li>
    <li><%= link_to "戻る", current_user %></li>
    <% end %>
    </ul>
   </div>
  </div>
  </header>
  <hr style="margin-top: -70px;">
   <h3 style="font-weight: bold; text-align: center;">投稿メモ検索結果</h3>
  <hr>
   <%= render @feed_items %>
<% end %>
<!-- impression_page.html.erbの検索バーからのパラメータ -->
<% unless @p_feed_items.nil? %>
<% if logged_in? %>
 <header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
   <div class="navbar-header">
    <%= link_to "REREC", root_path, id: "logo" %>
   </div>
   <ul class="nav navbar-nav navbar-right" style="margin-right:-50px;">
    <li class="search-nav">
     <%= form_with url: user_path(current_user), method: :get, local: true do %>
    <div class="input-group">
     <%= search_field_tag "p", params[:p], class: "form-control", placeholder: "読書メモ検索" %>
    <span class="input-group-btn">
     <%= submit_tag "検索", class: "btn btn-default" %>
    </span>
    </div>
     <% end %>
    </li>
    <li><%= link_to "戻る", current_user %></li>
     <% end %>
    </ul>
   </div>
  </div>
 </header>
  <hr style="margin-top: -70px;">
   <h3 style="font-weight: bold; text-align: center;">投稿メモ検索結果</h3>
  <hr>
   <%= render @p_feed_items %>
 <% end %>