config/routes.rb
Rails.application.routes.draw do

  get 'third_registers/create'
  get 'third_registers/destroy'
  get 'second_registers/create'
  get 'second_registers/destroy'
  get 'registers/create'
  get 'registers/destroy'
  get 'sessions/new'
  root 'home_pages#home'
  get '/about',   to: 'home_pages#about'
  get '/terms',     to: 'home_pages#terms'
  get '/privacy',  to: 'home_pages#privacy'
  get '/started_page',  to: 'home_pages#started_page'
  get '/signup',     to: 'users#new'
  post  '/signup',     to: 'users#create'
  get '/impressions_page',   to: 'users#impressions_page'
  get '/all_impressions_page',   to: 'users#all_impressions_page'
  get '/readed_books_table',   to: 'users#readed_books_table'
  get  '/login',     to: 'sessions#new'
  post  '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get  '/reading_books',  to:  'books#reading_books'
  get  '/readed_books',  to:  'books#readed_books'
  post  '/readed_books',  to:  'books#readed_books'
  get  '/want_books',  to:  'books#want_books'
  get  '/impressions_title',  to:  'impressions#impressions_title'
  post  '/impressions_title',  to:  'impressions#impressions_title'

  resources :users
  resources :impressions, only: %i[create destroy edit update]
  resources :registers, only: %i[create destroy]
  resources :second_registers, only: %i[create destroy]
  resources :third_registers, only: %i[create destroy]
  resources :books, only: %i[index create show] do
  	collection do
     get :search
    end		
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/views/partial_for_register_books/_register.html.erb
<div class="btn btn-sm btn font-s">
 <%= link_to registers_path(book_id: book.id), method: :post, local: true do %>
  <%= "読んでいる本に記録する" %></h4>
 <% end %>
</div>

app/views/partial_for_register_books/_register_area.html.erb
 <% if logged_in? %>
  <% if current_user.reading_book_register?(@book) %>
   <%= render 'partial_for_register_books/un_register', book: @book %>
  <% else %>
   <%= render 'partial_for_register_books/register', book: @book %>
  <% end %>
 <% end %>

app/views/partial_for_register_books/_second_register.html.erb
<div class="btn btn-sm btn font-s">
 <%= link_to second_registers_path(book_id: book.id), method: :post, local: true do %>
  <%= "読んだ本に記録する" %> 
 <% end %>
</div>

app/views/partial_for_register_books/_second_register_area.html.erb
<% if logged_in? %>
 <% if current_user.readed_book_register?(@book) %> 
　<%= render 'partial_for_register_books/un_second_register', book: @book %> 
 <% else %>
<%= render 'partial_for_register_books/second_register', book: @book %> 
 <% end %> 
<% end %> 

app/views/partial_for_register_books/_third_register.html.erb
<div class="btn btn-sm btn font-s">
 <%= link_to third_registers_path(book_id: book.id), method: :post, local: true do %> 
  <%= "読みたい本に記録する" %> 
 <% end %> 
</div>

app/views/partial_for_register_books/_third_register_area.html.erb
<% if logged_in? %>
 <% if current_user.want_book_register?(@book) %>
  <%= render 'partial_for_register_books/un_third_register', book: @book %>
 <% else %>
  <%= render 'partial_for_register_books/third_register', book: @book %>
 <% end %> 
<% end %>

app/views/partial_for_register_books/_un_register.html.erb
<div class="btn btn-sm btn font-s">
 <%= link_to register_path(current_user.registers.find_by(book_id: book.id)), method: :delete, local: true do %>
  <%= "読んでいる本から除外する" %>
 <% end %>
</div>

app/views/partial_for_register_books/_un_second_register.html.erb
<div class="btn btn-sm btn font-s">
 <%= link_to second_register_path(current_user.second_registers.find_by(book_id: book.id)), 
method: :delete, local: true do %>
  <%= "読んだ本から除外する" %> 
 <% end %>
</div>

app/views/partial_for_register_books/_un_third_register.html.erb
<div class="btn btn-sm btn font-s">
 <%= link_to third_register_path(current_user.third_registers.find_by(book_id: book.id)), 
method: :delete, local: true do %>
  <%= "読みたい本から除外する" %> 
 <% end %>
</div>