config/routes.rb
Rails.application.routes.draw do

  get 'third_registers/create'
  get 'third_registers/destroy'
  get 'second_registers/create'
  get 'second_registers/destroy'
  get 'registers/create'
  get 'registers/destroy'
  get 'sessions/new'
  root 'home_pages#home'
  get '/about',   to: 'home_pages#about'
  get '/terms',     to: 'home_pages#terms'
  get '/privacy',  to: 'home_pages#privacy'
  get '/started_page',  to: 'home_pages#started_page'
  get '/signup',     to: 'users#new'
  post  '/signup',     to: 'users#create'
  get '/impressions_page',   to: 'users#impressions_page'
  get '/all_impressions_page',   to: 'users#all_impressions_page'
  get '/readed_books_table',   to: 'users#readed_books_table'
  get  '/login',     to: 'sessions#new'
  post  '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get  '/reading_books',  to:  'books#reading_books'
  get  '/readed_books',  to:  'books#readed_books'
  post  '/readed_books',  to:  'books#readed_books'
  get  '/want_books',  to:  'books#want_books'
  get  '/impressions_title',  to:  'impressions#impressions_title'
  post  '/impressions_title',  to:  'impressions#impressions_title'

  resources :users
  resources :impressions, only: %i[create destroy edit update]
  resources :registers, only: %i[create destroy]
  resources :second_registers, only: %i[create destroy]
  resources :third_registers, only: %i[create destroy]
  resources :books, only: %i[index create show] do
  	collection do
     get :search
    end		
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/book.rb
# == Schema Information
  # create_table "books", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
  #   t.string "googlebooksapi_id", null: false
  #   t.string "title", null: false
  #   t.string "author"
  #   t.string "image"
  #   t.text "description"
  #   t.string "buy_link"
  #   t.bigint "user_id"
  #   t.date "published_at"
  #   t.datetime "created_at", null: false
  #   t.datetime "updated_at", null: false
  #   t.index ["googlebooksapi_id"], name: "index_books_on_googlebooksapi_id", unique: true
  #   t.index ["user_id", "created_at", "author", "title"], name: "index_books_on_user_id_and_created_at_and_author_and_title"
  #   t.index ["user_id"], name: "index_books_on_user_id"
  # end

class Book < ApplicationRecord
  # google books APIから取得したimageを保存する
  mount_uploader :image, ImageUploader
  has_many :users, through: :registers
  has_many :users, through: :second_registers
  has_many :users, through: :third_registers

  has_many :registers, dependent: :destroy
  has_many :second_registers, dependent: :destroy
  has_many :third_registers, dependent: :destroy
  has_many :multiple_authors, dependent: :destroy
  accepts_nested_attributes_for :registers
  accepts_nested_attributes_for :second_registers
  accepts_nested_attributes_for :third_registers

  validates :title, presence: true, length: { maximum: 255 }
  validates :googlebooksapi_id, presence: true,
                    length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :logged_in_user, only: [:create]
 
  def index
   @user = User.find(current_user.id)
   @books = Book.all
  end
  
  def create         #GoogleBook.new => google_book.rb
    google_book = GoogleBook.new_from_id(create_book_params[:googlebooksapi_id])
   if (@book = google_book.find_book_or_save)
    redirect_to @book
   else
    redirect_to search_books_path
    flash[:danger] = "ページの表示に失敗しました"
   end
  end

  def show
   @book = Book.find(params[:id])
   @books = Book.all
  end

  def reading_books
    @user = User.find(current_user.id)
    @books = @user.reading_books.order(updated_at: :desc)
    @book_paginate = Kaminari.paginate_array(@books).page(params[:page]).per(5)
    @users = @user.impressions
    @impressions = Kaminari.paginate_array(@users).page(params[:page]).per(5)
    @impression = current_user.impressions.build if logged_in?
  end

  def readed_books
   date = Date.today
   now = Time.current
   @user = User.find(current_user.id)
   @books = @user.readed_books.order(created_at: :desc)
   @book_paginate = Kaminari.paginate_array(@books).page(params[:page]).per(5)
   @books_created_at = @user.readed_books.pluck(:created_at)
   @page_count = @user.readed_books.pluck(:page_count).sum
   @book_count = @user.readed_books.count
   @now_month_count = @user.readed_books.where(created_at: date.beginning_of_month..date.end_of_month).count
   @month_page_count = @user.readed_books.where(created_at: date.beginning_of_month..date.end_of_month).pluck(:page_count).sum
   @month_book_count = SecondRegister.where(user_id: current_user.id).group("MONTH(created_at)").count
   @year_book_count = SecondRegister.where(user_id: current_user.id).group("YEAR(created_at)").count
   @users = @user.impressions
   @impressions = Kaminari.paginate_array(@users).page(params[:page])
   @impression = current_user.impressions.build if logged_in?
  end

  def want_books
   @user = User.find(current_user.id)
   @books = @user.want_books.order(updated_at: :desc)
   @book_paginate = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  end
  
  def search
   @search_form = SearchBooksForm.new(search_books_params)
   books = GoogleBook.search(@search_form.keyword)
   @books = Kaminari.paginate_array(books).page(params[:page]).per(5)
  end

private

	  def search_books_params
	   params.fetch(:q, keyword: '').permit(:keyword)
	  end

	  def create_book_params
	   params.permit(:googlebooksapi_id)
	  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="container.card.card-book" style="text-align:center;">
 <div class="row">
  <div class="col-2.col-md-3">
  <div style="margin: 0px 40px 8px;">
   <%= link_to book_path(book) do %>
    <%= image_tag book.image.url, width: '150' if book.image? %>
   <% end %>
  </div>
   <%= link_to book_path(book) do %>
    <%= "読書メモ/本の登録区分変更" %>
   <% end %><br>
    <div class="book-data">
    <ul class="wrap" style="list-style-type: none;">
     <li style="margin-left: 80px; margin-right: 5px;">著作：<span class="book"><%= book.title %></span></li>
     <li style="margin-left: 80px; margin-right: 5px;">著者：<span class="book"><%= book.author %></span></li>
     <% if request.path == reading_books_path %>
      <li style="margin-left: 80px; margin-right: 5px;">読み始めた日：<span class="book"><%= book.updated_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></span></li>
     <% elsif request.path == user_path(current_user) %>
      <li style="margin-left: 80px; margin-right: 5px;">読み始めた日：<span class="book"><%= book.updated_at.strftime("%Y年%-m月%-d日") %></span></li>
     <% elsif request.path == readed_books_path %>
      <li style="margin-left: 80px; margin-right: 5px;">読了日：<span class="book"><%= book.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></span></li>
     <% elsif request.path == want_books_path  %>
      <li style="margin-left: 80px; margin-right: 5px;">積本日：<span class="book"><%= book.updated_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></span></li>
       <% if book.description.present? %>
        <li style="margin-left: 80px; margin-right: 5px;">内容：<span class="book"><%= strip_tags book.description %></span></li>
       <% else %>
        <li style="margin-left: 80px; margin-right: 5px;">内容：<span class="book">情報がありません</span></li>
       <% end %>
      <% end %>
     <li style="margin-left: 80px; margin-right: 5px;">ページ数：<span class="book"><%= book.page_count %></span>ページ</li>
    </ul>
   </div>
  </div>
 </div>
</div>
<hr>

app/views/books/_book_searching.html.erb
<div class="container.card.card-book" style="text-align:center;">
 <div class="row">
  <div class="col-2.col-md-3">
   <hr>
   <%= link_to books_path(googlebooksapi_id: book.googlebooksapi_id), method: :post do %>
    <% if book.image? %>
     <%= image_tag book.image, height: '180' %>
    <% else %>
     <%= image_tag 'book-image.png', height: '180' %>
    <% end %>
   <% end %>
  </div>
   <%= link_to books_path(googlebooksapi_id: book.googlebooksapi_id), method: :post do %>
    <button type="button" class="btn btn-info w-25" style="margin-top:5px;">この本を選ぶ</button>
   <% end %>
  <div class="book-data">
   <ul class="wrap" style="list-style-type: none; margin-top: 12px;">
    <li style="margin-left: 30px; margin-right: 5px;">著作：<span class="book"><%= book.title %></span></li>
    <li style="margin-left: 30px; margin-right: 5px;">著者：<span class="book"><%= book.author %></span></li>
   <% if book.description.present? %>
    <li style="margin-left: 30px; margin-right: 10px;">内容：<span class="book"><%= strip_tags book.description %></span></li>
   <% else %>
    <li style="margin-left: 30px; margin-right: 5px;">内容：内容：<span class="book">情報がありません</span></li>
   <% end %>
    <li style="margin-left: 30px; margin-right: 5px;">ページ数：<span class="book"><%= book.page_count %></span>ページ</li>
   </ul>
   </div>
  </div>
 </div>
</div>

app/views/books/_books_searching.html.erb
<% if @books.any? %>
<hr style="margin-top: 50px;">
 <h3 style="font-weight: bold; text-align: center; margin-bottom: -40px; ">検索結果</h3>
<% end %>
<div class="container">
 <div class="row">
   <%= render partial: 'books/book_searching', collection: @books, as: :book %>
  <div class="mt-3">
   <%= paginate @books %>
  </div>
 </div>
</div>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/index.html.erb
<h1>本一覧</h1>
<% provide :title, "本一覧" %>
<div class="container">
 <div class="row">
  <%= render @books %>
 </div>
</div>

app/views/books/readed_books.html.erb
<% provide :title, "読んだ本" %>
  <div style="margin-top: -30px; text-align: center;">
   <%= link_to "本をさがす", search_books_path, class: "btn-border" %>
   <%= link_to "読んでいる本", reading_books_path, class: "btn-border-2" %>
   <%= link_to "読んだ本", readed_books_path, class: "btn-border-2" %>
   <%= link_to "読みたい本", want_books_path, class: "btn-border-2" %>
   <%= link_to "読書メモ確認", impressions_page_path, class: "btn-border" %>
   <%= link_to "読んだ本一覧", readed_books_table_path, class: "btn-border" %>
  </div>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読んだ本 -</h3>
 <% if @books.any? %>
  <%= render @book_paginate %>
  <%= paginate @book_paginate %>
 <% else %> 
  <p style="text-align: center;">現在読んだ本はありません</p>
 <% end %>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読んだ本の集計 -</h3>
<%# 表 %>
<table class="table-style" style="margin: 0 auto">
 <thead>
  <tr>
   <th><% now = Time.current %><%= now.month %>月に読んだ本</th>
   <th><% now = Time.current %><%= now.month %>月に読んだページ数</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td><%= @now_month_count %>冊</td>
   <td><%= @month_page_count %>ページ</td>
  </tr>
 </tbody>
</table>
<table class="table-style" style="margin: 0 auto">
  <tr>
   <th>読んだ月(月集計)</th>
   <th>読んだ数(月集計)</th>
  </tr>
 <tr>
  <td><% @month_book_count.keys.each do |month| %>
    <%= month %>月<br>
  <% end %></td>
  <td><% @month_book_count.values.each do |count| %>
   <%= count %>冊<br>
  <% end %></td>
 </tr>
</table>

<table class="table-style" style="margin: 0 auto">
 <tr>
  <th>読んだ年(年集計)</th>
  <th>読んだ数(年集計)</th>
 </tr>
 <tr>
  <td><% @year_book_count.keys.each do |year| %>
    <%= year %>年<br>
  <% end %></td>
  <td><% @year_book_count.values.each do |book| %>
    <%= book %>冊<br>
  <% end %></td>
 </tr>
</table>

<table class="table-style" style="margin: 0 auto">
 <thead>
  <tr>
   <th>読んだ本の総計</th>
   <th>読んだページ数</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td><%= @book_count %>冊</td>
   <td><%= @page_count %>ページ</td>
  </tr>
 </tbody>
</table>

app/views/books/reading_books.html.erb
<% provide :title, "読んでいる本" %>
  <div style="margin-top: -30px; text-align: center;">
   <%= link_to "本をさがす", search_books_path, class: "btn-border" %>
   <%= link_to "読んでいる本", reading_books_path, class: "btn-border-2" %>
   <%= link_to "読んだ本", readed_books_path, class: "btn-border-2" %>
   <%= link_to "読みたい本", want_books_path, class: "btn-border-2" %>
   <%= link_to "読書メモ確認", impressions_page_path, class: "btn-border" %>
   <%= link_to "読んだ本一覧", readed_books_table_path, class: "btn-border" %>
  </div>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読んでいる本 -</h3>
 <% if @books.any? %> 
  <%= render @book_paginate %>
  <%= paginate @book_paginate %>
 <% else %> 
  <p style="text-align: center;">現在読んでいる本はありません</p>
 <% end %>

app/views/books/search.erb
<% provide(:title, "本を検索する") %>
<% unless @books.any? %>
<div style="margin-top: -20px;">
<h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 本を検索する -</h3>
</div>
<% end %>
<div class="container search-nav-1">
  <%= form_with model: @search_form, url: search_books_path, scope: :q, local: true, method: :get do |f| %>
   <div class="input-group">
    <%= f.search_field :keyword, class: 'form-control', value: @search_form.keyword, placeholder: 'キーワードを入力してください' %>
   <span class="input-group-btn">
    <%= submit_tag "検索", class: "btn btn-default text-white" %>
   </span>
   <% end %>
   </div>
</div>
 <%= render 'books_searching', books: @books %>

app/views/books/show.html.erb
<% provide :title, "本を登録する" %>
<div style="text-align:center">
<h3 style="font-weight: bold;">読書メモ/本の登録</h3>
<% if @book.image? %>
 <%= image_tag @book.image.url, width: '150' %><br>
<% else %>
 <%= image_tag 'book-image.png', height: '150' %><br>
<% end %>
 <%= @book.title %>
 <%= @book.author %><br>
  <% if @book.buy_link.present? %>
   <button type="button" class="btn btn-info w-25" style="margin-top:15px;">
   <%= link_to @book.buy_link, target: :_blank do %>
   購入する
   </button>
   <% end %>
  <% end %><br>
 <%= render partial: 'shared/reading_from_search' %><br>
 <%= render partial: 'partial_for_register_books/register_area' %><br>
 <%= render partial: 'partial_for_register_books/second_register_area' %><br>
 <%= render partial: 'partial_for_register_books/third_register_area' %><br>
</div>
 

app/views/books/want_books.html.erb
<% provide :title, "読みたい本" %>
  <div style="margin-top: -30px; text-align: center;">
   <%= link_to "本をさがす", search_books_path, class: "btn-border" %>
   <%= link_to "読んでいる本", reading_books_path, class: "btn-border-2" %>
   <%= link_to "読んだ本", readed_books_path, class: "btn-border-2" %>
   <%= link_to "読みたい本", want_books_path, class: "btn-border-2" %>
   <%= link_to "読書メモ確認", impressions_page_path, class: "btn-border" %>
   <%= link_to "読んだ本一覧", readed_books_table_path, class: "btn-border" %>
  </div>
 <h3 style="font-weight: bold; text-align: center; margin: 40px 0;">- 読みたい本 -</h3>
 <% if @books.any? %> 
  <%= render @book_paginate %>
  <%= paginate @book_paginate %>
 <% else %>
  <p style="text-align: center;">現在読みたい本はありません</p>
 <% end %>