config/routes.rb
Rails.application.routes.draw do

  get 'third_registers/create'
  get 'third_registers/destroy'
  get 'second_registers/create'
  get 'second_registers/destroy'
  get 'registers/create'
  get 'registers/destroy'
  get 'sessions/new'
  root 'home_pages#home'
  get '/about',   to: 'home_pages#about'
  get '/terms',     to: 'home_pages#terms'
  get '/privacy',  to: 'home_pages#privacy'
  get '/started_page',  to: 'home_pages#started_page'
  get '/signup',     to: 'users#new'
  post  '/signup',     to: 'users#create'
  get '/impressions_page',   to: 'users#impressions_page'
  get '/all_impressions_page',   to: 'users#all_impressions_page'
  get '/readed_books_table',   to: 'users#readed_books_table'
  get  '/login',     to: 'sessions#new'
  post  '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  get  '/reading_books',  to:  'books#reading_books'
  get  '/readed_books',  to:  'books#readed_books'
  post  '/readed_books',  to:  'books#readed_books'
  get  '/want_books',  to:  'books#want_books'
  get  '/impressions_title',  to:  'impressions#impressions_title'
  post  '/impressions_title',  to:  'impressions#impressions_title'

  resources :users
  resources :impressions, only: %i[create destroy edit update]
  resources :registers, only: %i[create destroy]
  resources :second_registers, only: %i[create destroy]
  resources :third_registers, only: %i[create destroy]
  resources :books, only: %i[index create show] do
  	collection do
     get :search
    end		
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/views/layouts/_footer.html.erb
<!-- レスポンシブのみ表示 -->
	　<ul class="bottom-menu">
	   <li><%= link_to "RERECとは", about_path %></li>
	   <li><%= link_to "利用規約", terms_path %></li>
	   <li><%= link_to "プライバシー", privacy_path %></li>
	　</ul>
		<!-- PCデフォルト -->
　　<footer class="footer">
	<small>
		<a href="https://yo-suke-blog.com/" target="_blank">©2020 Yōsuke</a>
	</small>
	　<nav>
	　　<ul>
	     <li><%= link_to "RERECとは", about_path %></li>
	     <li><%= link_to "利用規約", terms_path %></li>
	     <li><%= link_to "プライバシー", privacy_path %></li>
	　　</ul>
	　</nav>
    </footer>

app/views/layouts/_for_ie.html.erb
<!-- for_ieパーシャル render 'layouts/for_ie' --> 
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/_head.html.erb
<!--headパーシャル render 'layouts/head'--> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag("rerec.ico") %>
　　 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
 <div class="container">
  <div class="navbar-header">
   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
   </button>
    <%= link_to "REREC", root_path, id: "logo" %>
  </div>
  <nav>
    <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
     <% if logged_in? %>
      <% if request.path == impressions_page_path %>
        <li class="search-nav">
          <%= form_with url: user_path(current_user), method: :get, local: true do %>
         <div class="input-group">
          <%= search_field_tag "p", params[:p], class: "form-control", placeholder: "読書メモ検索" %>
           <span class="input-group-btn">
            <%= submit_tag "検索", class: "btn btn-default" %>
           </span>
         </div>
          <% end %>
        </li>
      <% elsif request.path == all_impressions_page_path  %>
        <li class="search-nav">
          <%= form_with url: user_path(current_user), method: :get, local: true do %>
         <div class="input-group">
          <%= search_field_tag "i", params[:i], class: "form-control", placeholder: "読書メモ検索" %>
           <span class="input-group-btn">
            <%= submit_tag "検索", class: "btn btn-default" %>
           </span>
         </div>
          <% end %>
        </li>
      <% end %>

      <% unless request.path == readed_books_table_path %>
        <li>
         <%= link_to "マイページ", current_user %>
        </li>
        <li>
         <%= link_to "本をさがす", search_books_path %>
        </li>
        <li>
         <%= link_to "みんなの読書メモ", all_impressions_page_path %>
        </li>
      <% end %>

      <% if request.path == readed_books_table_path %>
        <li>
         <%= link_to "マイページに戻る", current_user %>
        </li>
      <% end %>
     <% end %>

   <!-- ログイン時のヘッダーメニュー -->
      <% if logged_in? %>
       <% if current_user.admin? %>
        <li> 
          <%= link_to "ユーザー管理画面", users_path %>
        </li>
       <% end %>
        <li>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        </li>
      <% else %>
       <li><%= link_to "はじめる", '/started_page' %></li>
     <% end %>
    </ul>
  </nav>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head' %>
    <%= render 'layouts/for_ie' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
   <div class="container">
    <% flash.each do |message_type, message| %>
     <%= content_tag(:div, message, class: "flash-margin alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
     <%#= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
   </div>
  </body>
</html>